import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {transform} from 'esbuild';
import * as rules from '../supabase/functions/_shared/contracts.js';
const unit='unit',org='org',day='2026-10-07';
const group={id:'group',business_unit_id:unit,active:true,contract_scope:'group',contract_group:'ersatzkassen',base_fee:2.4,price_per_km:2.1};
function database(contracts=[]){
 const rows={app_profiles:[{id:'user',organization_id:org,active:true}],business_units:[{id:unit,organization_id:org,code:'fahrdienst',active:true}],memberships:[{user_id:'user',business_unit_id:unit,active:true,role:'admin'}],health_insurers:[{id:'tk',name:'Techniker',organization_id:org,active:true}],payer_contracts:contracts,customer_insurances:[{id:'insurance',customer_id:'customer',exempt:false}],trips:[{id:'trip',business_unit_id:unit,service_date:day,trip_type:'Dialyse',from_address:'A',to_address:'B'}],customers:[{id:'customer',first_name:'Test',last_name:'Patient'}],contract_rates:[{contract_id:'group',active:true,position_code:'5130XX',sort_order:0}],trip_billing_cases:[{id:'case',trip_id:'trip',customer_id:'customer',business_unit_id:unit,insurance_id:'insurance',insurer_id:'tk',contract_id:'group',billing_status:'ready',billable_km:15,insurer_amount:33.9,position_code:'5130XX',treatment_code:'52',billing_position:'513052'}]};
 const writes=[];
 const db={auth:{getUser:async()=>({data:{user:{id:'user'}}})},from(table){let filters=[],single=false,patch=null,insert=null;
 const q={select(){return q},eq(k,v){filters.push(r=>r[k]===v);return q},not(k,op,v){filters.push(r=>r[k]!==v);return q},order(){return q},limit(){return q},maybeSingle(){single=true;return q},single(){single=true;return q},update(v){patch=v;return q},insert(v){insert=v;return q},delete(){return q},then(resolve,reject){try{let data=(rows[table]||[]).filter(r=>filters.every(f=>f(r)));if(patch){writes.push({table,patch});data=data.map(r=>Object.assign(r,patch));}if(insert){writes.push({table,insert});data=[{id:'new',document_seq:1,...insert}];}return Promise.resolve({data:single?data[0]||null:data,error:null}).then(resolve,reject);}catch(e){return Promise.reject(e).then(resolve,reject)}}};return q}};
 return {db,writes,rows};
}
async function handler(name,db){const source=fs.readFileSync(`supabase/functions/${name}/index.ts`,'utf8').replace(/^import .*;\n/gm,'');const {code}=await transform(source,{loader:'ts'});let handle;const Deno={env:{get:()=> 'test'},serve:f=>handle=f};new Function('Deno','createClient',...Object.keys(rules),code)(Deno,()=>db,...Object.values(rules));return handle;}
async function call(name,setup,body){const handle=await handler(name,setup.db);const response=await handle(new Request('https://example.test',{method:'POST',headers:{Authorization:'Bearer test','Content-Type':'application/json'},body:JSON.stringify({businessUnitCode:'fahrdienst',caseId:'case',...body})}));return {status:response.status,body:await response.json()};}
test('invoice cannot use stale ready status when contract is absent, inactive or expired',async()=>{for(const contracts of [[],[{...group,active:false}],[{...group,valid_until:'2026-10-06'}]]){const setup=database(contracts);const r=await call('manage-trip-billing',setup,{action:'invoice'});assert.equal(r.status,409);assert.equal(setup.writes.length,0);}});
test('new individual contract forces recalculation instead of billing old group',async()=>{const setup=database([group,{...group,id:'own',insurer_id:'tk',contract_scope:'individual'}]);const r=await call('manage-trip-billing',setup,{action:'invoice'});assert.equal(r.status,409);assert.match(r.body.error,/neu berechnen/);});
test('server recalculates against group and generates correct AOK-style position',async()=>{const setup=database([group]);const r=await call('manage-trip-billing',setup,{action:'recalculate',billableKm:15,positionCode:'5130XX',treatmentCode:'52',ownShareAmount:5});assert.equal(r.status,200);assert.equal(r.body.case.billing_status,'ready');assert.equal(r.body.case.billing_position,'513052');assert.equal(r.body.case.gross_amount,33.9);assert.equal(r.body.case.insurer_amount,28.9);});
test('server blocks recalculation without contract and incomplete template stays review',async()=>{let setup=database([]);let r=await call('manage-trip-billing',setup,{action:'recalculate'});assert.equal(r.body.case.billing_status,'blocked');setup=database([group]);r=await call('manage-trip-billing',setup,{action:'recalculate',treatmentCode:''});assert.equal(r.body.case.billing_status,'review');assert.equal(r.body.case.billing_position,null);});
test('valid case creates insurer invoice and links billing case',async()=>{const setup=database([group]);const r=await call('manage-trip-billing',setup,{action:'invoice'});assert.equal(r.status,200);assert.ok(setup.writes.some(w=>w.table==='invoices'));assert.ok(setup.writes.some(w=>w.table==='trip_billing_cases'&&w.patch?.billing_status==='invoiced'));});
test('manual insurer invoice cannot bypass missing contract',async()=>{const setup=database([]);const r=await call('manage-finance',setup,{action:'create_invoice',payerType:'insurer',insurerId:'tk',serviceDate:day,items:[{description:'Krankenfahrt',quantity:1,unitGross:30}]});assert.equal(r.status,409);assert.equal(setup.writes.length,0);});
