import BillingDocumentReview from '../../src/components/BillingDocumentReview.jsx';
import SubmissionRegister from '../../src/components/SubmissionRegister.jsx';
import {buildBillingBatch} from '../../src/lib/billingBatch.js';
import MonthlyCopay from '../../src/components/MonthlyCopay.jsx';
import TripHistory from '../../src/components/TripHistory.jsx';
import BillingBatch from '../../src/components/BillingBatch.jsx';
import LiveDispatchModal from '../../src/components/LiveDispatchModal.jsx';
import {privateFare} from '../../supabase/functions/_shared/copay.js';
import DocumentManagement from '../../src/components/DocumentManagement.jsx';
import {validateDocumentInput} from '../../supabase/functions/_shared/documents.js';
import BusinessSettings from '../../src/components/BusinessSettings.jsx';
import React from 'react';
import {createRoot} from 'react-dom/client';
import '../../src/styles.css';
import App from '../../src/App.jsx';
import ContractManagement from '../../src/components/ContractManagement.jsx';
import DriverPortal from '../../src/components/DriverPortal.jsx';
import ClientEditor from '../../src/components/ClientEditor.jsx';
import InvoiceManagement from '../../src/components/InvoiceManagement.jsx';
import ReceiptManagement from '../../src/components/ReceiptManagement.jsx';
import BillingManagement from '../../src/components/BillingManagement.jsx';
import LiveDispatchBoard from '../../src/components/LiveDispatchBoard.jsx';
const invoice={id:'invoice-test',invoice_number:'RE-TEST-001',payer_name:'Testkrankenkasse mit langem Namen',customer_name:'Erika Beispiel',issue_date:'2026-10-07',status:'open',net_total:19,vat_total:0,gross_total:19};
const invoiceItems=[{invoice_id:invoice.id,description:'513052 · Besetzte Kilometer',quantity:8,unit:'km',unit_gross:3,vat_rate:0,gross_total:24},{invoice_id:invoice.id,description:'Abzug Eigenanteil',quantity:1,unit:'Fahrt',unit_gross:-5,vat_rate:0,gross_total:-5},{invoice_id:'other',description:'FREMDRECHNUNG',gross_total:100}];
const finance={invoices:[invoice],invoiceItems,receipts:[{id:'r',receipt_number:'QU-TEST-001',received_from:'Erika Beispiel',receipt_type:'own_share',payment_method:'cash',payment_date:'2026-10-07',amount:5}],refresh:async()=>{},loading:false};
const correctionInvoice={id:'manual',invoice_number:'RE-MANUAL-001',payer_name:'Erika Beispiel',payer_type:'private',service_date:'2026-10-07',issue_date:'2026-10-07',status:'paid',gross_total:10,net_total:10,vat_total:0};
const correctionFinance={invoices:[correctionInvoice],invoiceItems:[{invoice_id:'manual',description:'Testfahrt',quantity:1,unit:'Fahrt',unit_gross:10,vat_rate:0,net_total:10,vat_total:0,gross_total:10}],refresh:async()=>{},loading:false};
const correctionApi={cancel:async(id,reason)=>{correctionInvoice.status='cancelled';const doc={...correctionInvoice,id:'storno',invoice_number:'ST-TEST-001',document_type:'cancellation',reversal_of_id:id,reference_invoice_number:correctionInvoice.invoice_number,cancellation_reason:reason,status:'open',gross_total:-10,net_total:-10,refund_amount:10,refund_status:'due'};correctionFinance.invoices=[...correctionFinance.invoices,doc];correctionFinance.invoiceItems.push({...correctionFinance.invoiceItems[0],invoice_id:'storno',unit_gross:-10,gross_total:-10,net_total:-10});return {ok:true,data:{id:'storno'}}},replace:async(id,input)=>{const doc={...correctionInvoice,id:'replacement',invoice_number:'RE-TEST-002',replaces_invoice_id:id,reference_invoice_number:correctionInvoice.invoice_number,status:'open',gross_total:input.items.reduce((s,l)=>s+Number(l.quantity)*Number(l.unitGross),0)};correctionFinance.invoices=[...correctionFinance.invoices,doc];correctionFinance.invoiceItems.push(...input.items.map(l=>({invoice_id:'replacement',description:l.description,quantity:l.quantity,unit:l.unit,unit_gross:l.unitGross,vat_rate:l.vatRate,gross_total:Number(l.quantity)*Number(l.unitGross)})));return {ok:true,data:{id:'replacement'}}},refund:async()=>{correctionFinance.invoices.find(i=>i.id==='storno').refund_status='refunded';return {ok:true,data:{}}}};
const billing={cases:[{id:'b',trip_id:'t',customer_id:'c',insurer_id:'i',billing_position:'513052',billable_km:8,gross_amount:24,own_share_amount:5,insurer_amount:19,billing_status:'ready'}],trips:[{id:'t',service_date:'2026-10-07',trip_type:'Dialyse'}],customers:[{id:'c',first_name:'Erika',last_name:'Beispiel'}],insurers:[{id:'i',name:'Testkrankenkasse'}],loading:false};
const billingFlow={...billing,cases:[{id:'private',trip_id:'private-trip',customer_id:'c',payer_type:'private',billing_status:'review',gross_amount:0,own_share_amount:0,insurer_amount:0,private_vat_rate:0},{id:'copay',trip_id:'hin',customer_id:'c',insurer_id:'i',payer_type:'insurer',billing_status:'ready',gross_amount:120,own_share_amount:10,insurer_amount:110,own_share_required:true,copay_rule_version:1,billing_position:'513052'},{id:'meter',trip_id:'return',customer_id:'c',insurer_id:'i',payer_type:'insurer',billing_status:'ready',gross_amount:120,own_share_amount:5,insurer_amount:115,own_share_required:true,copay_rule_version:1,billing_position:'514852'}],trips:[{id:'private-trip',service_date:'2026-10-08',trip_type:'Privatfahrt',direction:'outbound',from_address:'Test A',to_address:'Test B'},{id:'hin',service_date:'2026-10-08',trip_type:'Dialyse',direction:'outbound',from_address:'Test A',to_address:'Test B'},{id:'return',service_date:'2026-10-08',trip_type:'Dialyse',direction:'return',from_address:'Test B',to_address:'Test A'}],refresh:async()=>{}};
const billingFinance={invoices:[],receipts:[],invoiceItems:[],refresh:async()=>{}};
const billingApi={recalculate:async(item,input)=>{const fare=privateFare({amount:input.privateAmount,vatRate:input.privateVatRate});Object.assign(item,{private_amount:fare.gross,private_vat_rate:fare.vatRate,gross_amount:fare.gross,billing_status:'ready',copay_note:'Privatfahrt: Kunde zahlt den gesamten Fahrtbetrag.'});billingFlow.cases=[...billingFlow.cases];return item},invoice:async item=>{const fare=privateFare({amount:item.private_amount,vatRate:item.private_vat_rate});const id='private-invoice';billingFinance.invoices=[{id,invoice_number:'RE-PRIVATE-001',payer_name:'Erika Beispiel',payer_type:'private',issue_date:'2026-10-08',service_date:'2026-10-08',status:'open',gross_total:fare.gross,net_total:fare.net,vat_total:fare.vat}];billingFinance.invoiceItems=[{invoice_id:id,description:'Privatfahrt · Hinfahrt · Test A → Test B',quantity:1,unit:'Fahrt',unit_gross:fare.gross,vat_rate:fare.vatRate,gross_total:fare.gross}];Object.assign(item,{invoice_id:id,billing_status:'invoiced'});billingFlow.cases=[...billingFlow.cases];return {ok:true,data:{id}}},receipt:async(item,data,method)=>{document.body.dataset.receiptCalls=String(Number(document.body.dataset.receiptCalls||0)+1);const id='receipt-'+item.id;billingFinance.receipts=[...billingFinance.receipts,{id,receipt_number:'QU-'+item.id.toUpperCase(),received_from:'Erika Beispiel',purpose:item.id==='meter'?'Eigenanteil · Rückfahrt':'Eigenanteil · Hinfahrt',receipt_type:'own_share',payment_method:method,payment_date:'2026-10-08',amount:item.own_share_amount}];Object.assign(item,{receipt_id:id,own_share_paid:true});billingFlow.cases=[...billingFlow.cases];return {ok:true,data:{id}}}};
const batchFixture={data:{...billing,cases:[],trips:[]},finance:{invoices:[],invoiceItems:[]}};
for(const [id,direction,own] of [['batch-hin','outbound',10],['batch-return','return',5]]){
 batchFixture.data.cases.push({id,trip_id:id,customer_id:'c',insurer_id:'i',payer_type:'insurer',billing_status:'invoiced',invoice_id:id,gross_amount:120,own_share_amount:own,insurer_amount:120-own,copay_rule_version:1,direction_count:1,billing_position:own===5?'514852':'513052'});
 batchFixture.data.trips.push({id,service_date:'2026-10-08',status:'abgeschlossen',direction,from_address:'Test A',to_address:'Test B'});
 batchFixture.finance.invoices.push({id,invoice_number:'RE-'+id,payer_type:'insurer',insurer_id:'i',customer_id:'c',customer_name:'Erika Beispiel',service_date:'2026-10-08',status:'open',gross_total:120-own,issuer_snapshot:{company_name:'Testunternehmen',street:'Teststraße 1',postal_code:'12345',city:'Teststadt'}});
 batchFixture.finance.invoiceItems.push({id:'line-'+id,invoice_id:id,trip_id:id,gross_total:120-own});
}
batchFixture.data.cases.push({...batchFixture.data.cases[0],id:'batch-review',invoice_id:null,billing_status:'ready'});
const loadBatch=async()=>{const next=structuredClone(batchFixture);if(window.batchCancelled)next.finance.invoices[0].status='cancelled';return next};
const ownBilling={...billingFlow,cases:billingFlow.cases.filter(c=>c.id==='copay').map(c=>({...c}))};
const ownFinance={invoices:[],invoiceItems:[],receipts:[],refresh:async()=>{}};
const ownApi={...billingApi,ownInvoice:async(item,data,dueDate)=>{const id='own-patient-invoice';ownFinance.invoices=[{id,invoice_number:'RE-OWN-001',own_share_case_id:item.id,payer_type:'private',payer_name:'Erika Beispiel',payer_address:'Teststraße 1, 12345 Teststadt',customer_name:'Erika Beispiel',issue_date:'2026-10-08',due_date:dueDate,service_date:'2026-10-08',status:'open',gross_total:item.own_share_amount,net_total:item.own_share_amount,vat_total:0}];ownFinance.invoiceItems=[{invoice_id:id,trip_id:item.trip_id,description:'Eigenanteil · Hinfahrt · Test A → Test B',quantity:1,unit:'Fahrt',unit_gross:item.own_share_amount,vat_rate:0,gross_total:item.own_share_amount}];item.own_share_invoice_id=id;ownBilling.cases=[...ownBilling.cases];return {ok:true,data:{id}}}};
function OwnInvoiceFixture(){const [view,setView]=React.useState('billing');return <><button className="secondary-button" onClick={()=>setView(v=>v==='billing'?'invoices':'billing')}>{view==='billing'?'Rechnungen anzeigen':'Abrechnungen anzeigen'}</button>{view==='billing'?<BillingManagement data={ownBilling} financeData={ownFinance} api={ownApi} onFinanceRefresh={ownFinance.refresh}/>:<InvoiceManagement data={ownFinance} clients={[]} contracts={{insurers:[]}} onBillingRefresh={ownBilling.refresh} paymentApi={async()=>{document.body.dataset.paymentCalls=String(Number(document.body.dataset.paymentCalls||0)+1);ownFinance.invoices[0].status='paid';ownFinance.invoices=[...ownFinance.invoices];ownBilling.cases[0].own_share_paid=true;ownBilling.cases=[...ownBilling.cases];return {ok:true}}}/>}</>}
const d=new Date();const date=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const dispatch={trips:[{id:'t',date,time:'09:30',patient:'Erika Beispiel',type:'Dialyse',to:'Testadresse mit langem Straßennamen in Friedberg',driverId:'driver',driver:'Testfahrer',vehicle:'TEST-123',status:'geplant'}],loading:false};
const documentClients=[{id:'doc-customer',fullName:'Erika Beispiel',authorizations:[{id:'doc-approval',authorization_type:'approval',treatment_type:'Dialyse',approval_number:'TEST-123'}]}];
let fixtureDocuments=[{id:'original',customer_id:'doc-customer',kind:'prescription',title:'Testverordnung',file_name:'Testverordnung.png',mime_type:'image/png',size_bytes:68,status:'ready',uploaded_at:'2026-10-08T09:00:00Z'}];
const documentApi={list:async({customerId,kind,status})=>{const documents=fixtureDocuments.filter(d=>(!customerId||d.customer_id===customerId)&&(!kind||d.kind===kind)&&d.status===status);return {documents,total:documents.length}},upload:async(file,input)=>{validateDocumentInput({...input,fileName:file.name,mimeType:file.type,size:file.size});fixtureDocuments.push({id:crypto.randomUUID(),customer_id:input.customerId,kind:input.kind,title:input.title,file_name:file.name,mime_type:file.type,size_bytes:file.size,authorization_id:input.authorizationId,trip_id:input.tripId,status:'ready',uploaded_at:new Date().toISOString()})},archive:async id=>{fixtureDocuments.find(d=>d.id===id).status='archived'},restore:async id=>{fixtureDocuments.find(d=>d.id===id).status='ready'},link:async(id,input)=>{Object.assign(fixtureDocuments.find(d=>d.id===id),{title:input.title,authorization_id:input.authorizationId,trip_id:input.tripId})}};
const documentPreview=async id=>{const doc=fixtureDocuments.find(d=>d.id===id);return {url:location.origin+'/tests/ui/fixture-document.'+(doc.mime_type==='application/pdf'?'pdf':'png'),mimeType:doc.mime_type,fileName:doc.file_name}};
const screen=new URLSearchParams(location.search).get('screen');
const noop=()=>{};

function HistoryFixture(){
 const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Berlin'}).format(new Date());const [y,m]=today.split('-').map(Number);const month=new Date(Date.UTC(y,m-2,1)).toISOString().slice(0,7);
 const make=(id,day,direction,status='offen',customer='history-c')=>({id,customer_id:customer,customer_name:customer==='history-c'?'Erika Beispiel':'Anderer Patient',service_date:day,scheduled_time:direction==='return'?'13:00':'08:00',direction,status,trip_type:'Dialyse',from_address:'Teststraße A',to_address:'Dialysezentrum B',updated_at:'2026-10-08T09:00:00Z'});
 const rows=React.useRef([make('history-hin',month+'-02','outbound'),make('history-return',month+'-02','return'),make('history-exclude',month+'-04','outbound'),make('history-cancelled',month+'-07','outbound','storniert'),make('history-done',month+'-09','outbound','abgeschlossen'),make('history-other',month+'-11','outbound','offen','other'),make('history-future',new Date(Date.now()+86400000).toISOString().slice(0,10),'outbound')]);
 const load=React.useCallback(async({month,customerId})=>structuredClone(rows.current.filter(t=>t.service_date.startsWith(month)&&(!customerId||t.customer_id===customerId))),[]);
 const record=async(trips,decision,note)=>{if(document.body.dataset.historyFail==='true'){document.body.dataset.historyFail='false';throw Error('Fahrt wurde zwischenzeitlich geändert. Bitte Historie neu laden.');}document.body.dataset.historyCalls=String(Number(document.body.dataset.historyCalls||0)+1);document.body.dataset.historyIds=trips.map(t=>t.id).join(',');for(const t of rows.current)if(trips.some(x=>x.id===t.id)){t.status=decision;t.history_note=note;t.history_recorded_at=new Date().toISOString();}return {recorded:trips.length,alreadyRecorded:0};};
 return <TripHistory clients={[{id:'history-c',fullName:'Erika Beispiel'},{id:'other',fullName:'Anderer Patient'}]} load={load} record={record}/>;
}

function MonthlyFixture(){
 const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Berlin'}).format(new Date());const [y,m]=today.split('-').map(Number);const month=new Date(Date.UTC(y,m-2,1)).toISOString().slice(0,7);
 const initial=()=>{const cases=[10,10,5,5,10,10,0].map((own,i)=>({id:'monthly-'+i,trip_id:'mt-'+i,customer_id:'monthly-c',payer_type:'insurer',billing_status:'ready',copay_rule_version:1,own_share_amount:own,direction_count:1,updated_at:'2026-10-08T09:00:00Z',own_share_paid:i===4,own_share_invoice_id:i===5?'prior':null}));return {data:{cases,trips:cases.map((c,i)=>({id:c.trip_id,service_date:month+'-02',scheduled_time:i%2?'13:00':'08:00',status:'abgeschlossen',direction:i%2?'return':'outbound',trip_type:'Dialyse',from_address:'Test A',to_address:'Test B'})),customers:[{id:'monthly-c',first_name:'Erika',last_name:'Beispiel'}]},finance:{invoices:[],invoiceItems:[]}};};
 const state=React.useRef(initial());const load=React.useCallback(async()=>structuredClone(state.current),[]);
 const create=async(customer,month,cases,dueDate)=>{if(document.body.dataset.monthlyFail==='true'){document.body.dataset.monthlyFail='false';return {ok:false,message:'Fall wurde geändert. Neu laden.'};}document.body.dataset.monthlyCalls=String(Number(document.body.dataset.monthlyCalls||0)+1);document.body.dataset.monthlyCases=cases.map(c=>c.id).join(',');const total=cases.reduce((n,c)=>n+Number(c.own_share_amount),0);const doc={id:'monthly-doc',invoice_number:'RE-MONTH-001',customer_id:customer,payer_type:'private',payer_name:'Erika Beispiel',payer_address:'Teststraße 1, 12345 Teststadt',own_share_month:month+'-01',status:'open',issue_date:today,due_date:dueDate,gross_total:total,net_total:total,vat_total:0};state.current.finance.invoices.push(doc);for(const c of cases){const t=state.current.data.trips.find(t=>t.id===c.trip_id);state.current.finance.invoiceItems.push({invoice_id:doc.id,trip_id:t.id,description:month+'-02 · '+(t.direction==='return'?'Rückfahrt':'Hinfahrt'),quantity:1,unit:'Fahrt',gross_total:c.own_share_amount});state.current.data.cases.find(x=>x.id===c.id).own_share_invoice_id=doc.id;}return {ok:true,data:{id:doc.id}};};
 return <MonthlyCopay load={load} create={create}/>;
}
createRoot(document.getElementById('root')).render(screen==='shell'?<App/>:screen==='contracts'?<ContractManagement data={{insurers:[],contracts:[],rates:[],loading:false}}/>:screen==='driver'?<DriverPortal data={dispatch} user={{name:'Testfahrer',role:'driver'}} onLogout={noop}/>:screen==='client'?<ClientEditor onClose={noop} onSaved={noop}/>:<main className="page">{screen==='zadblocked'?<ZadFixture blocked/>:screen==='beleg'?<BelegFixture/>:screen==='zad'?<ZadFixture/>:screen==='monthly'?<MonthlyFixture/>:screen==='history'?<HistoryFixture/>:screen==='owninvoice'?<OwnInvoiceFixture/>:screen==='batch'?<BillingBatch load={loadBatch} save={async rows=>{batchFixture.submissions=[{id:'saved-zad',number:13,status:'prepared',rows_snapshot:rows}];return {number:13}}}/>:screen==='newtrip'?<LiveDispatchModal trips={[]} clients={[{id:'c',fullName:'Erika Beispiel'}]} drivers={[]} vehicles={[]} onClose={noop} onSaved={noop}/>:screen==='billingflow'?<BillingManagement data={billingFlow} financeData={billingFinance} onFinanceRefresh={billingFinance.refresh} api={billingApi}/>:screen==='documents'?<DocumentManagement clients={documentClients} trips={[{id:'doc-trip',customerId:'doc-customer',date:'2026-10-08',time:'09:00',type:'Dialyse'}]} api={documentApi} loadPreview={documentPreview}/>:screen==='settings'?<BusinessSettings loadProfile={async()=>({company_name:'Testunternehmen',street:'Teststraße 1',postal_code:'12345',city:'Teststadt',iban:'DE89370400440532013000'})} saveProfile={async()=>({ok:true})}/>:screen==='corrections'?<InvoiceManagement data={correctionFinance} clients={[]} contracts={{insurers:[]}} correctionApi={correctionApi}/>:screen==='invoices'?<InvoiceManagement data={finance} clients={[]} contracts={{insurers:[]}}/>:screen==='receipts'?<ReceiptManagement data={finance} clients={[]}/>:screen==='billing'?<BillingManagement data={billing}/>:<LiveDispatchBoard data={dispatch} drivers={[]} vehicles={[]} onEdit={()=>document.body.dataset.edited='yes'} onNew={noop}/>}</main>);

function ZadFixture({blocked=false}){
 const rows=buildBillingBatch(batchFixture.data,batchFixture.finance).filter(r=>!r.reason);
 const runsRef=React.useRef([{id:'zad-test',number:12,status:'prepared',created_at:new Date().toISOString(),rows_snapshot:rows,documentReports:rows.map(r=>({caseId:r.id,complete:!blocked}))}]);
 const load=React.useCallback(async()=>runsRef.current,[]);
 async function update(id,step,date,reference){if(window.zadFail){window.zadFail=false;throw Error('Rechnung geändert. Neu laden.')}document.body.dataset.zadCalls=String(Number(document.body.dataset.zadCalls||0)+1);runsRef.current=runsRef.current.map(r=>({...r,status:step==='web'?'web_entered':step==='post'?'posted':'discarded',...(step==='web'?{web_date:date,web_reference:reference}:step==='post'?{post_date:date,post_reference:reference}:{discard_reason:reference})}));}
 return <SubmissionRegister load={load} update={update}/>;
}

function BelegFixture(){
 const row=React.useRef({caseId:'beleg-case',customerId:'doc-customer',tripId:'doc-trip',patient:'Erika Beispiel',date:'2026-09-02',direction:'Hinfahrt',tripType:'Dialyse',complete:false,issues:['Belege noch nicht geprüft.'],reviewedAt:null,selection:null,candidates:[{id:'prescription-doc',title:'Dialyse-Verordnung September',kind:'prescription',authorization:{status:'valid',valid_from:'2026-09-01',valid_until:'2026-09-30'}},{id:'proof-doc',title:'Unterschriebener Transportnachweis',kind:'transport_proof',trip_id:'doc-trip'}]});
 const load=React.useCallback(async()=>[structuredClone(row.current)],[]);
 async function save(target,selection){if(window.belegFail){window.belegFail=false;throw Error('Beleg seit Auswahl geändert. Neu laden.')}row.current={...row.current,selection,complete:true,issues:[],reviewedAt:new Date().toISOString()};document.body.dataset.belegCalls=String(Number(document.body.dataset.belegCalls||0)+1);}
 return <BillingDocumentReview load={load} save={save}/>;
}
