import BusinessSettings from '../../src/components/BusinessSettings.jsx';
import React from 'react';
import {createRoot} from 'react-dom/client';
import '../../src/styles.css';
import App from '../../src/App.jsx';
import ContractManagement from '../../src/components/ContractManagement.jsx';
import DriverPortal from '../../src/components/DriverPortal.jsx';
import ClientEditor from '../../src/components/ClientEditor.jsx';
import InvoiceManagement from '../../src/components/InvoiceManagement.jsx';
import ReceiptManagement from '../../src/components/ReceiptManagement.jsx';
import BillingManagement from '../../src/components/BillingManagement.jsx';
import LiveDispatchBoard from '../../src/components/LiveDispatchBoard.jsx';
const invoice={id:'invoice-test',invoice_number:'RE-TEST-001',payer_name:'Testkrankenkasse mit langem Namen',customer_name:'Erika Beispiel',issue_date:'2026-10-07',status:'open',net_total:19,vat_total:0,gross_total:19};
const invoiceItems=[{invoice_id:invoice.id,description:'513052 · Besetzte Kilometer',quantity:8,unit:'km',unit_gross:3,vat_rate:0,gross_total:24},{invoice_id:invoice.id,description:'Abzug Eigenanteil',quantity:1,unit:'Fahrt',unit_gross:-5,vat_rate:0,gross_total:-5},{invoice_id:'other',description:'FREMDRECHNUNG',gross_total:100}];
const finance={invoices:[invoice],invoiceItems,receipts:[{id:'r',receipt_number:'QU-TEST-001',received_from:'Erika Beispiel',receipt_type:'own_share',payment_method:'cash',payment_date:'2026-10-07',amount:5}],refresh:async()=>{},loading:false};
const billing={cases:[{id:'b',trip_id:'t',customer_id:'c',insurer_id:'i',billing_position:'513052',billable_km:8,gross_amount:24,own_share_amount:5,insurer_amount:19,billing_status:'ready'}],trips:[{id:'t',service_date:'2026-10-07',trip_type:'Dialyse'}],customers:[{id:'c',first_name:'Erika',last_name:'Beispiel'}],insurers:[{id:'i',name:'Testkrankenkasse'}],loading:false};
const d=new Date();const date=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const dispatch={trips:[{id:'t',date,time:'09:30',patient:'Erika Beispiel',type:'Dialyse',to:'Testadresse mit langem Straßennamen in Friedberg',driverId:'driver',driver:'Testfahrer',vehicle:'TEST-123',status:'geplant'}],loading:false};
const screen=new URLSearchParams(location.search).get('screen');
const noop=()=>{};
createRoot(document.getElementById('root')).render(screen==='shell'?<App/>:screen==='contracts'?<ContractManagement data={{insurers:[],contracts:[],rates:[],loading:false}}/>:screen==='driver'?<DriverPortal data={dispatch} user={{name:'Testfahrer',role:'driver'}} onLogout={noop}/>:screen==='client'?<ClientEditor onClose={noop} onSaved={noop}/>:<main className="page">{screen==='settings'?<BusinessSettings loadProfile={async()=>({company_name:'Testunternehmen',street:'Teststraße 1',postal_code:'12345',city:'Teststadt',iban:'DE89370400440532013000'})} saveProfile={async()=>({ok:true})}/>:screen==='invoices'?<InvoiceManagement data={finance} clients={[]} contracts={{insurers:[]}}/>:screen==='receipts'?<ReceiptManagement data={finance} clients={[]}/>:screen==='billing'?<BillingManagement data={billing}/>:<LiveDispatchBoard data={dispatch} drivers={[]} vehicles={[]} onEdit={()=>document.body.dataset.edited='yes'} onNew={noop}/>}</main>);
