import React,{useMemo,useState} from 'react';
import {BadgeEuro,CheckCircle2,FileWarning,ReceiptText,RefreshCw,Save,X} from 'lucide-react';
import {createCaseInvoice,createOwnShareReceipt,recalculateCase} from '../data/billing.js';
const euro=v=>Number(v||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const status={review:'Prüfen',ready:'Bereit',invoiced:'Abgerechnet',completed:'Erledigt',blocked:'Gesperrt'};
export default function BillingManagement({data,onFinanceRefresh}){
 const[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const tripById=useMemo(()=>Object.fromEntries(data.trips.map(x=>[x.id,x])),[data.trips]),customerById=useMemo(()=>Object.fromEntries(data.customers.map(x=>[x.id,x])),[data.customers]),insurerById=useMemo(()=>Object.fromEntries(data.insurers.map(x=>[x.id,x])),[data.insurers]);
 const totals=useMemo(()=>({review:data.cases.filter(x=>x.billing_status==='review').length,ready:data.cases.filter(x=>x.billing_status==='ready').length,gross:data.cases.reduce((s,x)=>s+Number(x.gross_amount||0),0)}),[data.cases]);
 async function recalc(e){e.preventDefault();setBusy(true);setError('');try{const fd=Object.fromEntries(new FormData(e.currentTarget).entries());await recalculateCase(selected,fd,data);setSelected(null);await data.refresh();}catch(x){setError(x.message||'Berechnung fehlgeschlagen.')}finally{setBusy(false)}}
 async function invoice(item){setBusy(true);setError('');const r=await createCaseInvoice(item,data);if(!r.ok)setError(r.message);else{await Promise.all([data.refresh(),onFinanceRefresh?.()]);}setBusy(false)}
 async function receipt(item){setBusy(true);setError('');const r=await createOwnShareReceipt(item,data,'cash');if(!r.ok)setError(r.message);else{await Promise.all([data.refresh(),onFinanceRefresh?.()]);}setBusy(false)}
 return <section className="billing-page">
  <div className="billing-kpis"><div><FileWarning/><span><strong>{totals.review}</strong>zu prüfen</span></div><div><CheckCircle2/><span><strong>{totals.ready}</strong>bereit</span></div><div><BadgeEuro/><span><strong>{euro(totals.gross)}</strong>Fahrtenwert</span></div></div>
  {error&&<div className="users-error">{error}</div>}{data.error&&<div className="users-error">{data.error}</div>}
  <div className="billing-table">
   <div className="billing-row billing-head"><span>Fahrt</span><span>Patient / Kasse</span><span>Position</span><span>km</span><span>Gesamt</span><span>Eigenanteil</span><span>Kasse</span><span>Status</span><span>Aktion</span></div>
   {data.loading?<div className="users-loading">Abrechnungsfälle werden geladen …</div>:data.cases.map(item=>{const t=tripById[item.trip_id]||{},c=customerById[item.customer_id]||{},i=insurerById[item.insurer_id]||{};return <div className="billing-row" key={item.id}>
    <div><b>{t.service_date||'—'}</b><small>{t.trip_type||'Krankenfahrt'}</small></div><div><b>{[c.first_name,c.last_name].filter(Boolean).join(' ')||'—'}</b><small>{i.short_name||i.name||'Privat / offen'}</small></div><b>{item.billing_position||item.position_code||'—'}</b><span>{item.billable_km??'—'}</span><b>{euro(item.gross_amount)}</b><span>{euro(item.own_share_amount)}</span><b>{euro(item.insurer_amount)}</b><span className={'billing-status '+item.billing_status}>{status[item.billing_status]||item.billing_status}</span>
    <div className="billing-actions"><button className="text-button" onClick={()=>{setError('');setSelected(item)}}>Prüfen</button>{item.billing_status==='ready'&&!item.invoice_id&&<button className="text-button" disabled={busy} onClick={()=>invoice(item)}>Rechnung</button>}{item.own_share_required&&!item.own_share_paid&&<button className="text-button" disabled={busy} onClick={()=>receipt(item)}>Zuzahlung</button>}</div>
   </div>})}
   {!data.loading&&!data.cases.length&&<div className="module-empty"><ReceiptText/><h3>Noch keine Abrechnungsfälle</h3><p>Sobald eine Krankenfahrt abgeschlossen wird, erscheint sie hier automatisch zur Prüfung.</p></div>}
  </div>
  {selected&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setSelected(null)}/><form className="modal-card compact-modal" onSubmit={recalc}><div className="modal-head"><div><p className="eyebrow">ABRECHNUNG PRÜFEN</p><h2>{customerById[selected.customer_id]?.first_name} {customerById[selected.customer_id]?.last_name}</h2></div><button type="button" className="icon-button" onClick={()=>setSelected(null)}><X/></button></div>
   <div className="form-grid"><label><span>Abrechnungs-km</span><input name="billableKm" type="number" step="0.1" defaultValue={selected.billable_km??''}/></label><label><span>Wartezeit Minuten</span><input name="waitingMinutes" type="number" min="0" defaultValue={selected.waiting_minutes||0}/></label><label><span>Positionsnummer</span><input name="positionCode" defaultValue={selected.position_code||''}/></label><label><span>Fahrtart-Code</span><input name="treatmentCode" defaultValue={selected.treatment_code||''} placeholder="52 Dialyse · 05 ambulant"/></label><label><span>Eigenanteil €</span><input name="ownShareAmount" type="number" step="0.01" min="0" defaultValue={selected.own_share_amount||0}/></label><label><span>Aktuelle Kassenposition</span><input disabled value={selected.billing_position||'wird berechnet'}/></label></div>
   {selected.review_message&&<div className="billing-review-note">{selected.review_message}</div>}{error&&<div className="users-error">{error}</div>}<div className="modal-actions"><span/><button type="button" className="secondary-button" onClick={()=>setSelected(null)}>Abbrechen</button><button className="primary-button" disabled={busy}><Save size={17}/>{busy?'Berechnet …':'Neu berechnen & speichern'}</button></div></form></div>}
 </section>;
}