import React,{useMemo,useState} from 'react';
import {BadgeEuro,Building2,Plus,Save,ShieldCheck,X,Pencil} from 'lucide-react';
import {saveContract,saveInsurer,saveRate} from '../data/contracts.js';
import {insurerGroup,validOn} from '../../supabase/functions/_shared/contracts.js';
const money=v=>Number(v||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const groups={aok:'AOK – eigener Vertrag',dak:'DAK – eigener Vertrag',ersatzkassen:'Ersatzkassenvertrag',individual:'Nur eigener Vertrag'};
export default function ContractManagement({data}){
 const [mode,setMode]=useState('contracts'),[modal,setModal]=useState(null),[scope,setScope]=useState('individual'),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const insurers=useMemo(()=>Object.fromEntries(data.insurers.map(x=>[x.id,x])),[data.insurers]);
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin'}).format(new Date());
 const open=(type,row={})=>{setError('');setScope(row.contract_scope||'individual');setModal({type,row});};
 async function submit(e){e.preventDefault();setSaving(true);setError('');const fd=Object.fromEntries(new FormData(e.currentTarget));fd.active=fd.active==='true';
 const r=modal.type==='insurer'?await saveInsurer({...fd,insurerId:modal.row.id}):modal.type==='contract'?await saveContract({...fd,contractId:modal.row.id,contractScope:scope}):await saveRate({...fd,rateId:modal.row.id,contractId:modal.row.contract_id});
 setSaving(false);if(!r.ok){setError(r.message);return;}setModal(null);await data.refresh();}
 const row=modal?.row||{};
 const field=(name,label,column,type='text',fallback='')=><label key={name}><span>{label}</span><input name={name} type={type} step={type==='number'?'0.01':undefined} min={type==='number'?'0':undefined} defaultValue={row[column]??fallback}/></label>;
 return <section className="contracts-page">
 <div className="module-toolbar"><div className="module-tabs"><button className={mode==='contracts'?'active':''} onClick={()=>setMode('contracts')}>Verträge</button><button className={mode==='insurers'?'active':''} onClick={()=>setMode('insurers')}>Krankenkassen</button></div><div className="heading-actions"><button className="secondary-button" onClick={()=>open('insurer')}><Plus size={17}/> Krankenkasse</button><button className="primary-button" onClick={()=>open('contract')}><Plus size={17}/> Vertrag</button></div></div>
 {data.error&&<div className="users-error">{data.error}</div>}
 <p className="billing-review-note">Ein gültiger Einzelvertrag hat Vorrang. Weitere Kassen werden über den Ersatzkassenvertrag abgerechnet. AOK und DAK benötigen eigene Verträge. Ohne gültigen Vertrag bleibt die Abrechnung gesperrt.</p>
 <div className="contract-kpis"><div><ShieldCheck/><span><strong>{data.insurers.length}</strong>Krankenkassen</span></div><div><Building2/><span><strong>{data.contracts.filter(c=>validOn(c,today)).length}</strong>gültige Verträge</span></div><div><BadgeEuro/><span><strong>{data.rates.length}</strong>Tarifpositionen</span></div></div>
 <div className="contract-grid">{mode==='insurers'?data.insurers.map(i=><article className="contract-card" key={i.id}><div className="contract-card-head"><div><small>{groups[insurerGroup(i)]}</small><h3>{i.short_name||i.name}</h3></div><span className={i.active?'active-tag':'inactive-tag'}>{i.active?'Aktiv':'Inaktiv'}</span></div><p>{i.name}</p><dl><div><dt>IK</dt><dd>{i.ik_number||'—'}</dd></div><div><dt>Abrechnung</dt><dd>{i.billing_email||i.billing_contact||'—'}</dd></div></dl><button className="text-button" onClick={()=>open('insurer',i)}><Pencil size={14}/> Bearbeiten</button></article>):data.contracts.map(c=><article className="contract-card" key={c.id}><div className="contract-card-head"><div><small>{c.contract_scope==='group'?'Ersatzkassen · Gruppenvertrag':insurers[c.insurer_id]?.short_name||insurers[c.insurer_id]?.name||'Einzelvertrag'}</small><h3>{c.contract_name}</h3></div><span className={validOn(c,today)?'active-tag':'inactive-tag'}>{!c.active?'Inaktiv':validOn(c,today)?'Gültig':'Außerhalb Gültigkeit'}</span></div><p>{c.contract_number||'Keine Vertragsnummer'}</p><dl><div><dt>Grundpreis</dt><dd>{money(c.base_fee)}</dd></div><div><dt>je km</dt><dd>{money(c.price_per_km)}</dd></div><div><dt>Gültig ab</dt><dd>{c.valid_from||'Unbefristet'}</dd></div><div><dt>Gültig bis</dt><dd>{c.valid_until||'Unbefristet'}</dd></div></dl><div className="rate-list">{data.rates.filter(r=>r.contract_id===c.id).map(r=><span key={r.id}><b>{r.position_code}</b>{r.label} · {money(r.price)}/{r.unit} <button className="text-button" onClick={()=>open('rate',r)}><Pencil size={12}/></button></span>)}</div><div className="heading-actions"><button className="text-button" onClick={()=>open('contract',c)}><Pencil size={14}/> Bearbeiten</button><button className="text-button" onClick={()=>open('rate',{contract_id:c.id})}>+ Tarifposition</button></div></article>)}</div>
 {!data.loading&&!(mode==='insurers'?data.insurers:data.contracts).length&&<div className="module-empty"><ShieldCheck/><h3>Noch keine {mode==='insurers'?'Krankenkassen':'Verträge'}</h3><p>Hinterlege eure echten Verträge und Preise. Ein Gruppenvertrag gilt für alle entsprechend zugeordneten Kassen.</p></div>}
 {modal&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setModal(null)}/><form className="modal-card compact-modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">KASSEN & VERTRÄGE</p><h2>{modal.type==='insurer'?'Krankenkasse':modal.type==='contract'?'Vertrag':'Tarifposition'} {row.id?'bearbeiten':'anlegen'}</h2></div><button type="button" className="icon-button" onClick={()=>setModal(null)}><X/></button></div>
 <div className="form-grid">
 {modal.type==='insurer'?<>
 <label><span>Name</span><input name="name" required defaultValue={row.name||''}/></label>{field('shortName','Kurzname','short_name')}{field('ikNumber','IK-Nummer','ik_number')}{field('billingEmail','Abrechnung E-Mail','billing_email','email')}
 <label><span>Vertragszuordnung</span><select name="contractGroup" defaultValue={row.id?insurerGroup(row):'ersatzkassen'}>{Object.entries(groups).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>
 </>:modal.type==='contract'?<>
 <label><span>Vertragsumfang</span><select value={scope} onChange={e=>setScope(e.target.value)}><option value="individual">Einzelvertrag einer Krankenkasse</option><option value="group">Ersatzkassen – Gruppenvertrag</option></select></label>
 {scope==='individual'?<label><span>Krankenkasse</span><select name="insurerId" required defaultValue={row.insurer_id||''}><option value="">Auswählen</option>{data.insurers.map(i=><option value={i.id} key={i.id}>{i.short_name||i.name}</option>)}</select></label>:<input type="hidden" name="contractGroup" value="ersatzkassen"/>}
 <label><span>Vertragsname</span><input name="contractName" required defaultValue={row.contract_name||''}/></label>{field('contractNumber','Vertragsnummer','contract_number')}
 <label><span>Abrechnungsart</span><select name="billingMethod" defaultValue={row.billing_method||'individual'}><option value="individual">Einzelabrechnung</option><option value="flat_rate">Pauschale</option><option value="mixed">Gemischt</option></select></label>
 {field('validFrom','Gültig ab','valid_from','date')}{field('validUntil','Gültig bis','valid_until','date')}{field('baseFee','Grundpreis €','base_fee','number',0)}{field('pricePerKm','Preis / km €','price_per_km','number',0)}{field('waitingPerHour','Wartezeit / h €','waiting_per_hour','number',0)}{field('wheelchairSurcharge','Rollstuhl-Zuschlag €','wheelchair_surcharge','number',0)}
 <input type="hidden" name="copayMin" value={row.copay_min??5}/><input type="hidden" name="copayMax" value={row.copay_max??10}/><input type="hidden" name="copayPercent" value={row.copay_percent??10}/>
 </>:<><label><span>Positionsnummer / Vorlage</span><input name="positionCode" defaultValue={row.position_code||''} placeholder="z. B. 5130XX"/></label><label><span>Bezeichnung</span><input name="label" required defaultValue={row.label||''}/></label><label><span>Einheit</span><select name="unit" defaultValue={row.unit||'ride'}><option value="ride">Fahrt</option><option value="km">km</option><option value="hour">Stunde</option><option value="minute">Minute</option><option value="flat">Pauschale</option></select></label>{field('price','Preis €','price','number',0)}</>}
 <label><span>Status</span><select name="active" defaultValue={row.active===false?'false':'true'}><option value="true">Aktiv</option><option value="false">Inaktiv</option></select></label>
 {modal.type!=='rate'&&<label className="wide"><span>Notiz</span><textarea name="notes" rows="2" defaultValue={row.notes||''}/></label>}
 </div>{error&&<div className="users-error">{error}</div>}<div className="modal-actions"><span/><button type="button" className="secondary-button" onClick={()=>setModal(null)}>Abbrechen</button><button className="primary-button" disabled={saving}><Save size={17}/>{saving?'Speichert …':'Speichern'}</button></div></form></div>}
 </section>;
}
