import React,{useMemo,useState} from 'react';
import {BadgeEuro,Building2,Plus,Save,ShieldCheck,X} from 'lucide-react';
import {saveContract,saveInsurer,saveRate} from '../data/contracts.js';

const money=v=>Number(v||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const emptyInsurer={name:'',shortName:'',ikNumber:'',billingContact:'',billingEmail:'',billingPhone:'',notes:'',active:true};
const emptyContract={insurerId:'',contractName:'',contractNumber:'',validFrom:'',validUntil:'',billingMethod:'individual',baseFee:'0',pricePerKm:'0',waitingPerHour:'0',wheelchairSurcharge:'0',copayMin:'5',copayMax:'10',copayPercent:'10',notes:'',active:true};

export default function ContractManagement({data}){
 const [mode,setMode]=useState('contracts'),[modal,setModal]=useState(null),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const insurerById=useMemo(()=>Object.fromEntries(data.insurers.map(x=>[x.id,x])),[data.insurers]);
 async function submit(e){e.preventDefault();setSaving(true);setError('');const fd=Object.fromEntries(new FormData(e.currentTarget).entries());let r;
  if(modal==='insurer')r=await saveInsurer({...fd,active:true});
  else if(modal==='contract')r=await saveContract({...fd,active:true});
  else r=await saveRate({...fd,active:true});
  setSaving(false);if(!r.ok){setError(r.message);return;}setModal(null);await data.refresh();
 }
 return <section className="contracts-page">
  <div className="module-toolbar"><div className="module-tabs"><button className={mode==='contracts'?'active':''} onClick={()=>setMode('contracts')}>Verträge</button><button className={mode==='insurers'?'active':''} onClick={()=>setMode('insurers')}>Krankenkassen</button></div><div className="heading-actions"><button className="secondary-button" onClick={()=>setModal('insurer')}><Plus size={17}/> Krankenkasse</button><button className="primary-button" onClick={()=>setModal('contract')} disabled={!data.insurers.length}><Plus size={17}/> Vertrag</button></div></div>
  {data.error&&<div className="users-error">{data.error}</div>}
  <div className="contract-kpis"><div><ShieldCheck/><span><strong>{data.insurers.length}</strong>Krankenkassen</span></div><div><Building2/><span><strong>{data.contracts.filter(x=>x.active).length}</strong>aktive Verträge</span></div><div><BadgeEuro/><span><strong>{data.rates.length}</strong>Tarifpositionen</span></div></div>
  {mode==='insurers'?<div className="contract-grid">{data.insurers.map(i=><article className="contract-card" key={i.id}><div className="contract-card-head"><div><small>Kostenträger</small><h3>{i.short_name||i.name}</h3></div><span className={i.active?'active-tag':'inactive-tag'}>{i.active?'Aktiv':'Inaktiv'}</span></div><p>{i.name}</p><dl><div><dt>IK</dt><dd>{i.ik_number||'—'}</dd></div><div><dt>Abrechnung</dt><dd>{i.billing_email||i.billing_contact||'—'}</dd></div></dl></article>)}</div>:
  <div className="contract-grid">{data.contracts.map(c=>{const rates=data.rates.filter(r=>r.contract_id===c.id);return <article className="contract-card" key={c.id}><div className="contract-card-head"><div><small>{insurerById[c.insurer_id]?.short_name||insurerById[c.insurer_id]?.name||'Krankenkasse'}</small><h3>{c.contract_name}</h3></div><span className={c.active?'active-tag':'inactive-tag'}>{c.active?'Aktiv':'Inaktiv'}</span></div><p>{c.contract_number||'Keine Vertragsnummer'}</p><dl><div><dt>Grundpreis</dt><dd>{money(c.base_fee)}</dd></div><div><dt>je km</dt><dd>{money(c.price_per_km)}</dd></div><div><dt>Wartezeit / h</dt><dd>{money(c.waiting_per_hour)}</dd></div><div><dt>Gültig ab</dt><dd>{c.valid_from||'—'}</dd></div></dl><div className="rate-list">{rates.map(r=><span key={r.id}>{r.position_code&&<b>{r.position_code}</b>}{r.label} · {money(r.price)}/{r.unit}</span>)}</div><button className="text-button" onClick={()=>setModal({type:'rate',contractId:c.id})}>+ Tarifposition</button></article>})}</div>}
  {!data.loading&&!((mode==='insurers'?data.insurers:data.contracts).length)&&<div className="module-empty"><ShieldCheck/><h3>Noch keine {mode==='insurers'?'Krankenkassen':'Verträge'}</h3><p>Lege die Daten hier zentral an. Preise werden nicht automatisch erfunden, sondern aus euren echten Verträgen übernommen.</p></div>}
  {modal&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setModal(null)}/><form className="modal-card compact-modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">KASSEN & VERTRÄGE</p><h2>{modal==='insurer'?'Krankenkasse anlegen':modal==='contract'?'Vertrag anlegen':'Tarifposition anlegen'}</h2></div><button type="button" className="icon-button" onClick={()=>setModal(null)}><X/></button></div>
   {modal==='insurer'?<div className="form-grid"><label><span>Name</span><input name="name" required/></label><label><span>Kurzname</span><input name="shortName"/></label><label><span>IK-Nummer</span><input name="ikNumber"/></label><label><span>Abrechnung E-Mail</span><input name="billingEmail" type="email"/></label><label className="wide"><span>Notiz</span><textarea name="notes" rows="3"/></label></div>:
   modal==='contract'?<div className="form-grid"><label><span>Krankenkasse</span><select name="insurerId" required><option value="">Auswählen</option>{data.insurers.map(i=><option value={i.id} key={i.id}>{i.short_name||i.name}</option>)}</select></label><label><span>Vertragsname</span><input name="contractName" required/></label><label><span>Vertragsnummer</span><input name="contractNumber"/></label><label><span>Abrechnungsart</span><select name="billingMethod"><option value="individual">Einzelabrechnung</option><option value="flat_rate">Pauschale</option><option value="mixed">Gemischt</option></select></label><label><span>Gültig ab</span><input name="validFrom" type="date"/></label><label><span>Gültig bis</span><input name="validUntil" type="date"/></label><label><span>Grundpreis €</span><input name="baseFee" type="number" step="0.01" defaultValue="0"/></label><label><span>Preis / km €</span><input name="pricePerKm" type="number" step="0.01" defaultValue="0"/></label><label><span>Wartezeit / h €</span><input name="waitingPerHour" type="number" step="0.01" defaultValue="0"/></label><label><span>Rollstuhl-Zuschlag €</span><input name="wheelchairSurcharge" type="number" step="0.01" defaultValue="0"/></label><label className="wide"><span>Notiz</span><textarea name="notes" rows="2"/></label></div>:
   <div className="form-grid"><input type="hidden" name="contractId" value={modal.contractId}/><label><span>Positionsnummer</span><input name="positionCode"/></label><label><span>Bezeichnung</span><input name="label" required/></label><label><span>Einheit</span><select name="unit"><option value="ride">Fahrt</option><option value="km">km</option><option value="hour">Stunde</option><option value="minute">Minute</option><option value="flat">Pauschale</option></select></label><label><span>Preis €</span><input name="price" type="number" step="0.01" required/></label></div>}
   {error&&<div className="users-error">{error}</div>}<div className="modal-actions"><span/><button type="button" className="secondary-button" onClick={()=>setModal(null)}>Abbrechen</button><button className="primary-button" disabled={saving}><Save size={17}/>{saving?'Speichert …':'Speichern'}</button></div></form></div>}
 </section>;
}
